/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.commons.mail.DefaultAuthenticator;
import org.apache.commons.mail.EmailException;
import org.apache.commons.mail.HtmlEmail;

/**
 *
 * @author pj
 */
public class Mail {
    private String destinataireEmail;
    private String destinataireNom;
    private String sujet;
    private String contenu;
    private HtmlEmail email;
    public Mail(String destinataireEmail, String destinataireNom, String sujet) {
        this.destinataireEmail=destinataireEmail;
        this.destinataireNom=destinataireNom;
        this.sujet=sujet;
        this.contenu="";
    }
    public void send() {
        try {
            email=new HtmlEmail();
            email.setHostName("localhost");
            email.setSmtpPort(25);
            email.setAuthenticator(new DefaultAuthenticator("noreply@le-bon-troc.fr", "paradize"));
            email.addTo(this.destinataireEmail, this.destinataireNom);
            email.setFrom("noreply@le-bon-troc.fr", "Le bon troc");
            email.setSubject(this.sujet);
            email.setHtmlMsg(this.contenu);
            email.send();
        } catch (EmailException ex) {
            Logger.getLogger(Mail.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    public void initMailInscription(String pseudo, String email, String motDePasse) {
        this.contenu="<html";
        this.contenu+="<head>";
        this.contenu+="<style type=\"text/css\">";
        this.contenu+="body {";
        this.contenu+="font-family: Arial,Serif;";
	this.contenu+="background-color: #ffffff;";
        this.contenu+="}";
        this.contenu+="div,p {";
	this.contenu+="font-size: 11px; {";
	this.contenu+="font-size: 11px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h1 {";
	this.contenu+="font-size: 15px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h2 {";
        this.contenu+="font-size: 13px;";
        this.contenu+="color: #111111;";
        this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="div.info {";
        this.contenu+="background-color: #a1978d;";
        this.contenu+="font-weight: 600;";
        this.contenu+="color: #333333;";
        this.contenu+="}";
        this.contenu+="a {";
        this.contenu+="font-size: #12px;";
        this.contenu+="color: #0000cc;";
        this.contenu+="font-weight: 700;";
        this.contenu+="}";
        this.contenu+="a:hover {";
        this.contenu+="color: #cc0000;";
        this.contenu+="text-decoration: none;";
        this.contenu+="}";
        this.contenu+="</style>";
        this.contenu+="</head>";
        this.contenu+="<body>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<br/>";
    this.contenu+="<h1 align=\"center\">"+Datas.TITRESITE+" -- Inscription</h1>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<div class=\"info\">Vous êtes désormais inscrit(e) sur "+Datas.TITRESITE+".</div>";
    this.contenu+="<br/>";
    this.contenu+="<div>Voici vos identifiants :</div>";
    this.contenu+="<br/>";
    this.contenu+="<div>Adresse Email : "+email+"</div>";
    this.contenu+="<div>Pseudonyme :"+pseudo+"</div>";
    this.contenu+="<div>Mot de passe : "+motDePasse+"</div>";
    this.contenu+="<br/>";
    this.contenu+="<div><a href=\""+Datas.URLROOT+"\">"+Datas.URLROOT+"</a>";
    this.contenu+="<br/>";
    this.contenu+="<br/>";
    this.contenu+="<div class=\"info\">Ceci est un mail automatique, inutile d'y répondre.</div>";
    this.contenu+="<br/>";
    this.contenu+="</body>";
    this.contenu+="</html>";
    }
    public void initMailNouveauMdp(String pseudo, String email, String motDePasse) {
        this.contenu="<html";
        this.contenu+="<head>";
        this.contenu+="<style type=\"text/css\">";
        this.contenu+="body {";
        this.contenu+="font-family: Arial,Serif;";
	this.contenu+="background-color: #ffffff;";
        this.contenu+="}";
        this.contenu+="div,p {";
	this.contenu+="font-size: 11px; {";
	this.contenu+="font-size: 11px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h1 {";
	this.contenu+="font-size: 15px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h2 {";
        this.contenu+="font-size: 13px;";
        this.contenu+="color: #111111;";
        this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="div.info {";
        this.contenu+="background-color: #a1978d;";
        this.contenu+="font-weight: 600;";
        this.contenu+="color: #333333;";
        this.contenu+="}";
        this.contenu+="a {";
        this.contenu+="font-size: #12px;";
        this.contenu+="color: #0000cc;";
        this.contenu+="font-weight: 700;";
        this.contenu+="}";
        this.contenu+="a:hover {";
        this.contenu+="color: #cc0000;";
        this.contenu+="text-decoration: none;";
        this.contenu+="}";
        this.contenu+="</style>";
        this.contenu+="</head>";
        this.contenu+="<body>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<br/>";
    this.contenu+="<h1 align=\"center\">"+Datas.TITRESITE+" -- Nouveau mot de passe</h1>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<div class=\"info\">Cher(e) "+pseudo+", vous avez demandé un nouveau mot de passe.</div>";
    this.contenu+="<br/>";
    this.contenu+="<div>Voici vos identifiants :</div>";
    this.contenu+="<br/>";
    this.contenu+="<div>Adresse Email : "+email+"</div>";
    this.contenu+="<div>Pseudonyme :"+pseudo+"</div>";
    this.contenu+="<div>Mot de passe : "+motDePasse+"</div>";
    this.contenu+="<br/>";
    this.contenu+="<div>Vous pouvez changer ce mot de passe ici : <a href=\""+Datas.URLROOT+"/infos-personnelles.html\">"+Datas.URLROOT+"/infos-personnelles.html</a>";
    this.contenu+="<br/>";
    this.contenu+="<br/>";
    this.contenu+="<div class=\"info\">Ceci est un mail automatique, inutile d'y répondre.</div>";
    this.contenu+="<br/>";
    this.contenu+="</body>";
    this.contenu+="</html>";
    }
    public void initMailNouveauMdp2(String pseudo, String email, String motDePasse) {
        this.contenu="<html";
        this.contenu+="<head>";
        this.contenu+="<style type=\"text/css\">";
        this.contenu+="body {";
        this.contenu+="font-family: Arial,Serif;";
	this.contenu+="background-color: #ffffff;";
        this.contenu+="}";
        this.contenu+="div,p {";
	this.contenu+="font-size: 11px; {";
	this.contenu+="font-size: 11px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h1 {";
	this.contenu+="font-size: 15px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h2 {";
        this.contenu+="font-size: 13px;";
        this.contenu+="color: #111111;";
        this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="div.info {";
        this.contenu+="background-color: #a1978d;";
        this.contenu+="font-weight: 600;";
        this.contenu+="color: #333333;";
        this.contenu+="}";
        this.contenu+="a {";
        this.contenu+="font-size: #12px;";
        this.contenu+="color: #0000cc;";
        this.contenu+="font-weight: 700;";
        this.contenu+="}";
        this.contenu+="a:hover {";
        this.contenu+="color: #cc0000;";
        this.contenu+="text-decoration: none;";
        this.contenu+="}";
        this.contenu+="</style>";
        this.contenu+="</head>";
        this.contenu+="<body>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<br/>";
    this.contenu+="<h1 align=\"center\">"+Datas.TITRESITE+" -- Nouveau mot de passe</h1>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<div class=\"info\">Cher(e) "+pseudo+", vous avez changé de mot de passe.</div>";
    this.contenu+="<br/>";
    this.contenu+="<div>Voici vos identifiants :</div>";
    this.contenu+="<br/>";
    this.contenu+="<div>Adresse Email : "+email+"</div>";
    this.contenu+="<div>Pseudonyme :"+pseudo+"</div>";
    this.contenu+="<div>Mot de passe : "+motDePasse+"</div>";
    this.contenu+="<br/>";
    this.contenu+="<div><a href=\""+Datas.URLROOT+"\">"+Datas.URLROOT+"</a>";
    this.contenu+="<br/>";
    this.contenu+="<br/>";
    this.contenu+="<div class=\"info\">Ceci est un mail automatique, inutile d'y répondre.</div>";
    this.contenu+="<br/>";
    this.contenu+="</body>";
    this.contenu+="</html>";
    }
    public void initMailAnnonce1(String pseudo, String titreAnnonce, String uri, long idAnnonce) {
        this.contenu="<html";
        this.contenu+="<head>";
        this.contenu+="<style type=\"text/css\">";
        this.contenu+="body {";
        this.contenu+="font-family: Arial,Serif;";
	this.contenu+="background-color: #ffffff;";
        this.contenu+="}";
        this.contenu+="div,p {";
	this.contenu+="font-size: 11px; {";
	this.contenu+="font-size: 11px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h1 {";
	this.contenu+="font-size: 15px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h2 {";
        this.contenu+="font-size: 13px;";
        this.contenu+="color: #111111;";
        this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="div.info {";
        this.contenu+="background-color: #a1978d;";
        this.contenu+="font-weight: 600;";
        this.contenu+="color: #333333;";
        this.contenu+="}";
        this.contenu+="a {";
        this.contenu+="font-size: #12px;";
        this.contenu+="color: #0000cc;";
        this.contenu+="font-weight: 700;";
        this.contenu+="}";
        this.contenu+="a:hover {";
        this.contenu+="color: #cc0000;";
        this.contenu+="text-decoration: none;";
        this.contenu+="}";
        this.contenu+="</style>";
        this.contenu+="</head>";
        this.contenu+="<body>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<br/>";
    this.contenu+="<h1 align=\"center\">"+Datas.TITRESITE+" -- Annonce publiée !</h1>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<div class=\"info\">Cher(e) "+pseudo+", votre annonce : \""+titreAnnonce+"\" vient d'être publiée sur "+Datas.TITRESITE+".</div>";
    this.contenu+="<br/>";
    this.contenu+="<div>Elle est visible à cette adresse : <a href=\""+Datas.URLROOT+"/"+uri+"\">"+Datas.URLROOT+"/"+uri+"</a></div>";
    this.contenu+="<br/>";
    this.contenu+="<div>Vous pourrez l'éditer à cette adresse : <a href=\""+Datas.URLROOT+"/edit-annonce-"+idAnnonce+".html\">"+Datas.URLROOT+"/edit-annonce-"+idAnnonce+".html</a></div>";
    this.contenu+="<br/>";
    this.contenu+="<div><a href=\""+Datas.URLROOT+"\">"+Datas.URLROOT+"</a>";
    this.contenu+="<br/>";
    this.contenu+="<br/>";
    this.contenu+="<div class=\"info\">Ceci est un mail automatique, inutile d'y répondre.</div>";
    this.contenu+="<br/>";
    this.contenu+="</body>";
    this.contenu+="</html>";
    }
    public void initMailAnnonceModif1(String pseudo, String titreAnnonce, String uri, long idAnnonce) {
        this.contenu="<html";
        this.contenu+="<head>";
        this.contenu+="<style type=\"text/css\">";
        this.contenu+="body {";
        this.contenu+="font-family: Arial,Serif;";
	this.contenu+="background-color: #ffffff;";
        this.contenu+="}";
        this.contenu+="div,p {";
	this.contenu+="font-size: 11px; {";
	this.contenu+="font-size: 11px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h1 {";
	this.contenu+="font-size: 15px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h2 {";
        this.contenu+="font-size: 13px;";
        this.contenu+="color: #111111;";
        this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="div.info {";
        this.contenu+="background-color: #a1978d;";
        this.contenu+="font-weight: 600;";
        this.contenu+="color: #333333;";
        this.contenu+="}";
        this.contenu+="a {";
        this.contenu+="font-size: #12px;";
        this.contenu+="color: #0000cc;";
        this.contenu+="font-weight: 700;";
        this.contenu+="}";
        this.contenu+="a:hover {";
        this.contenu+="color: #cc0000;";
        this.contenu+="text-decoration: none;";
        this.contenu+="}";
        this.contenu+="</style>";
        this.contenu+="</head>";
        this.contenu+="<body>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<br/>";
    this.contenu+="<h1 align=\"center\">"+Datas.TITRESITE+" -- Annonce modifiée !</h1>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<div class=\"info\">Cher(e) "+pseudo+", votre annonce : \""+titreAnnonce+"\" vient d'être modifiée sur "+Datas.TITRESITE+".</div>";
    this.contenu+="<br/>";
    this.contenu+="<div>Elle est visible à cette adresse : <a href=\""+Datas.URLROOT+"/annonce-"+idAnnonce+"-"+uri+"\">"+Datas.URLROOT+"/annonce-"+idAnnonce+"-"+uri+"</a></div>";
    this.contenu+="<br/>";
    this.contenu+="<div>Vous pourrez l'éditer à cette adresse : <a href=\""+Datas.URLROOT+"/edit-annonce-"+idAnnonce+".html\">"+Datas.URLROOT+"/edit-annonce-"+idAnnonce+".html</a></div>";
    this.contenu+="<br/>";
    this.contenu+="<div><a href=\""+Datas.URLROOT+"\">"+Datas.URLROOT+"</a>";
    this.contenu+="<br/>";
    this.contenu+="<br/>";
    this.contenu+="<div class=\"info\">Ceci est un mail automatique, inutile d'y répondre.</div>";
    this.contenu+="<br/>";
    this.contenu+="</body>";
    this.contenu+="</html>";
    }
    public void initMailAbus(long idAbus) {
        this.contenu="<html";
        this.contenu+="<head>";
        this.contenu+="<style type=\"text/css\">";
        this.contenu+="body {";
        this.contenu+="font-family: Arial,Serif;";
	this.contenu+="background-color: #ffffff;";
        this.contenu+="}";
        this.contenu+="div,p {";
	this.contenu+="font-size: 11px; {";
	this.contenu+="font-size: 11px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h1 {";
	this.contenu+="font-size: 15px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h2 {";
        this.contenu+="font-size: 13px;";
        this.contenu+="color: #111111;";
        this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="div.info {";
        this.contenu+="background-color: #a1978d;";
        this.contenu+="font-weight: 600;";
        this.contenu+="color: #333333;";
        this.contenu+="}";
        this.contenu+="a {";
        this.contenu+="font-size: #12px;";
        this.contenu+="color: #0000cc;";
        this.contenu+="font-weight: 700;";
        this.contenu+="}";
        this.contenu+="a:hover {";
        this.contenu+="color: #cc0000;";
        this.contenu+="text-decoration: none;";
        this.contenu+="}";
        this.contenu+="</style>";
        this.contenu+="</head>";
        this.contenu+="<body>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<br/>";
    this.contenu+="<h1 align=\"center\">"+Datas.TITRESITE+" -- Abus signalé !</h1>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<div class=\"info\">Un abus a été signalé.</div>";
    this.contenu+="<br/>";
    this.contenu+="<div>pour le traiter : <a href=\""+Datas.URLROOT+"/nimdo/abus-"+idAbus+".html\">"+Datas.URLROOT+"/nimdo/abus-"+idAbus+".html</a></div>";
    this.contenu+="<br/>";
    this.contenu+="<br/>";
    this.contenu+="<br/>";
    this.contenu+="<div class=\"info\">Ceci est un mail automatique, inutile d'y répondre.</div>";
    this.contenu+="<br/>";
    this.contenu+="</body>";
    this.contenu+="</html>";
    }
    public void initMailMessage1(String pseudoMembreExpediteur, String pseudoMembreDestinataire, String objetMsg, long idMessage) {
        this.contenu="<html";
        this.contenu+="<head>";
        this.contenu+="<style type=\"text/css\">";
        this.contenu+="body {";
        this.contenu+="font-family: Arial,Serif;";
	this.contenu+="background-color: #ffffff;";
        this.contenu+="}";
        this.contenu+="div,p {";
	this.contenu+="font-size: 11px; {";
	this.contenu+="font-size: 11px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h1 {";
	this.contenu+="font-size: 15px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h2 {";
        this.contenu+="font-size: 13px;";
        this.contenu+="color: #111111;";
        this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="div.info {";
        this.contenu+="background-color: #a1978d;";
        this.contenu+="font-weight: 600;";
        this.contenu+="color: #333333;";
        this.contenu+="}";
        this.contenu+="a {";
        this.contenu+="font-size: #12px;";
        this.contenu+="color: #0000cc;";
        this.contenu+="font-weight: 700;";
        this.contenu+="}";
        this.contenu+="a:hover {";
        this.contenu+="color: #cc0000;";
        this.contenu+="text-decoration: none;";
        this.contenu+="}";
        this.contenu+="</style>";
        this.contenu+="</head>";
        this.contenu+="<body>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<br/>";
    this.contenu+="<h1 align=\"center\">"+Datas.TITRESITE+" -- Message envoyé !</h1>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<div>Cher(e), "+pseudoMembreExpediteur+", votre message a bien été envoyé à "+pseudoMembreDestinataire+".</div>";
    this.contenu+="<br/>";
    this.contenu+="<div class=\"info\">Objet du message : "+objetMsg+".</div>";
    this.contenu+="<br/>";
    this.contenu+="<div>Pour le visualiser RDV ici : <a href=\""+Datas.URLROOT+"/message-envoye-"+idMessage+".html\">"+Datas.URLROOT+"/message-envoye-"+idMessage+".html</a></div>";
    this.contenu+="<br/>";
    this.contenu+="<br/>";
    this.contenu+="<br/>";
    this.contenu+="<div class=\"info\">Ceci est un mail automatique, inutile d'y répondre.</div>";
    this.contenu+="<br/>";
    this.contenu+="</body>";
    this.contenu+="</html>";
    }
    public void initMailMessage2(String pseudoMembreExpediteur, String pseudoMembreDestinataire, String objetMsg, long idMessage) {
        this.contenu="<html";
        this.contenu+="<head>";
        this.contenu+="<style type=\"text/css\">";
        this.contenu+="body {";
        this.contenu+="font-family: Arial,Serif;";
	this.contenu+="background-color: #ffffff;";
        this.contenu+="}";
        this.contenu+="div,p {";
	this.contenu+="font-size: 11px; {";
	this.contenu+="font-size: 11px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h1 {";
	this.contenu+="font-size: 15px;";
	this.contenu+="color: #000000;";
	this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="h2 {";
        this.contenu+="font-size: 13px;";
        this.contenu+="color: #111111;";
        this.contenu+="font-weight: 600;";
        this.contenu+="}";
        this.contenu+="div.info {";
        this.contenu+="background-color: #a1978d;";
        this.contenu+="font-weight: 600;";
        this.contenu+="color: #333333;";
        this.contenu+="}";
        this.contenu+="a {";
        this.contenu+="font-size: #12px;";
        this.contenu+="color: #0000cc;";
        this.contenu+="font-weight: 700;";
        this.contenu+="}";
        this.contenu+="a:hover {";
        this.contenu+="color: #cc0000;";
        this.contenu+="text-decoration: none;";
        this.contenu+="}";
        this.contenu+="</style>";
        this.contenu+="</head>";
        this.contenu+="<body>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<br/>";
    this.contenu+="<h1 align=\"center\">"+Datas.TITRESITE+" -- Nouveau message !</h1>";
    this.contenu+="<br/>";
    this.contenu+="<hr/>";
    this.contenu+="<div>Cher(e), "+pseudoMembreDestinataire+", "+pseudoMembreExpediteur+" vous a envoyé un nouveau message.</div>";
    this.contenu+="<br/>";
    this.contenu+="<div class=\"info\">Objet du message : "+objetMsg+".</div>";
    this.contenu+="<br/>";
    this.contenu+="<div>Pour le visualiser RDV ici : <a href=\""+Datas.URLROOT+"/message-recu-"+idMessage+".html\">"+Datas.URLROOT+"/message-recu-"+idMessage+".html</a></div>";
    this.contenu+="<br/>";
    this.contenu+="<br/>";
    this.contenu+="<br/>";
    this.contenu+="<div class=\"info\">Ceci est un mail automatique, inutile d'y répondre.</div>";
    this.contenu+="<br/>";
    this.contenu+="</body>";
    this.contenu+="</html>";
    }
}
